In [1]:
import os
import sys
from pathlib import Path
import logging

# Ensure the project root and src/ are on PYTHONPATH.
project_root = Path.cwd().resolve()
if project_root.name == "src":
    project_root = project_root.parent
src_dir = project_root / "src"
for path_entry in (project_root, src_dir):
    if str(path_entry) not in sys.path:
        sys.path.insert(0, str(path_entry))

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Force CPU usage
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"  # Reduce TensorFlow native logs

import pandas as pd
import tensorflow as tf
from utils import train_and_forecast

tf.config.set_visible_devices([], "GPU")  # Disable GPU inside TensorFlow
print("GPUS: ", tf.config.list_physical_devices("GPU"))

# Reduce repeated utility logs during notebook training.
for logger_name in ("utils.data_utils", "src.utils.data_utils"):
    logging.getLogger(logger_name).setLevel(logging.WARNING)

# ============================================================================
# GLOBAL SETTINGS
# ============================================================================

# Available models: 'RNN', 'LSTM', or 'CNN'
MODEL_NAME = "RNN"

# Forecast horizon: 3 or 12 months
FORECAST_HORIZON = 3

# Fixed training parameters
LOOK_BACK = 12
EPOCHS = 150
BATCH_SIZE = 1
SAVE_ONNX = True
SILENCE_TRAINING = True

# Regions and product series
REGIONS = ["ilheus", "itabuna"]
PRODUCTS = [
    "acucar",
    "arroz",
    "banana",
    "cafe",
    "carne",
    "farinha",
    "feijao",
    "leite",
    "manteiga",
    "oleo",
    "pao",
    "tomate",
]

GPUS:  []

2026-08-31 16:35:45.137756: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

# Previsão preço da cesta básica

## Treinamento de modelos

### Cesta Básica

In [2]:
# Basic basket forecast

print(f"Training basic basket: {MODEL_NAME}, {FORECAST_HORIZON}-month horizon")

basket_summary = []
for region in REGIONS:
    basket_summary.append(
        train_and_forecast(
            region=region,
            series_name="cesta_basica",
            forecast_type="cesta",
            model_name=MODEL_NAME,
            look_back=LOOK_BACK,
            forecast_horizon=FORECAST_HORIZON,
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            save_onnx=SAVE_ONNX,
            silence_training=SILENCE_TRAINING,
        )
    )

pd.DataFrame(basket_summary)

Training basic basket: RNN, 3-month horizon

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1788204988.713963  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788204988.714087  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788204988.743951  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788204988.744095  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788204988.771073  382806 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
I0000 00:00:1788205031.657906  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205031.657971  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205031.684935  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205031.685003  382806 single_machine.cc:376] Starting new session

    region        series  samples  final_loss                 forecasts
0   ilheus  cesta_basica      246    0.000613  [587.86, 580.01, 594.63]
1  itabuna  cesta_basica      246    0.000431  [597.68, 603.46, 606.58]

### Produtos Individuais

In [3]:
# Product forecasts

total_models = len(REGIONS) * len(PRODUCTS)
print(
    f"Training products: {MODEL_NAME}, {FORECAST_HORIZON}-month horizon "
    f"({total_models} models)"
)

product_summary = []
for region in REGIONS:
    print(f"{region.upper()}: training {len(PRODUCTS)} products...")
    for product in PRODUCTS:
        product_summary.append(
            train_and_forecast(
                region=region,
                series_name=product,
                forecast_type="produtos",
                model_name=MODEL_NAME,
                look_back=LOOK_BACK,
                forecast_horizon=FORECAST_HORIZON,
                epochs=EPOCHS,
                batch_size=BATCH_SIZE,
                save_onnx=SAVE_ONNX,
                silence_training=SILENCE_TRAINING,
                subdir="produtos",
            )
        )
    print(f"{region.upper()}: done")

pd.DataFrame(product_summary)

Training products: RNN, 3-month horizon (24 models)
ILHEUS: training 12 products...

I0000 00:00:1788205075.665454  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205075.665529  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205075.692351  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205075.692405  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205117.612001  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205117.612067  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205117.637571  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205117.637627  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205159.597244  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205159.597311  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205159.624322  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205159.624376  382806 single_machine.cc:376] Starting new session

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x787ec878aac0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

I0000 00:00:1788205201.504789  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205201.504913  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205201.533693  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205201.533745  382806 single_machine.cc:376] Starting new session

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x787fd1f9dda0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

I0000 00:00:1788205243.849422  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205243.849489  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205243.876156  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205243.876216  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205286.986272  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205286.986338  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205287.011976  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205287.012033  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205330.624456  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205330.624590  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205330.655425  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205330.655481  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205373.578287  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205373.578383  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205373.614877  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205373.615023  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205417.097635  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205417.097702  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205417.128970  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205417.129112  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205460.203735  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205460.203811  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205460.233913  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205460.233969  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205503.278928  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205503.278995  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205503.308746  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205503.308815  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205546.873103  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205546.873187  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205546.900415  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205546.900467  382806 single_machine.cc:376] Starting new session

ILHEUS: done
ITABUNA: training 12 products...

I0000 00:00:1788205590.102585  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205590.102702  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205590.130288  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205590.130346  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205633.252814  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205633.252881  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205633.281706  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205633.281760  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205677.594173  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205677.594304  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205677.626745  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205677.626835  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205720.939729  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205720.939795  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205720.965538  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205720.965591  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205764.368042  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205764.368163  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205764.395050  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205764.395162  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205808.199628  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205808.199768  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205808.227312  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205808.227365  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205851.586077  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205851.586210  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205851.613278  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205851.613329  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205895.006541  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205895.006605  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205895.033601  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205895.033657  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205938.670420  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205938.670547  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205938.699021  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205938.699107  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205983.350571  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205983.350697  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788205983.378120  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788205983.378178  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788206027.627468  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788206027.627534  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788206027.656774  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788206027.656883  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788206070.265049  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788206070.265114  382806 single_machine.cc:376] Starting new session
I0000 00:00:1788206070.292265  382806 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1788206070.292322  382806 single_machine.cc:376] Starting new session

ITABUNA: done

     region    series  samples  final_loss                 forecasts
0    ilheus    acucar      246    0.000002     [12.04, 11.53, 11.77]
1    ilheus     arroz      246    0.000005     [18.01, 17.54, 17.04]
2    ilheus    banana      246    0.000036      [50.11, 50.0, 49.45]
3    ilheus      cafe      246    0.000002     [17.17, 19.61, 18.07]
4    ilheus     carne      246    0.000124  [205.82, 193.58, 208.19]
5    ilheus   farinha      246    0.000004      [25.0, 25.29, 24.98]
6    ilheus    feijao      246    0.000023     [41.46, 40.43, 39.15]
7    ilheus     leite      246    0.000010     [62.16, 62.28, 61.81]
8    ilheus  manteiga      246    0.000006     [38.64, 36.96, 36.38]
9    ilheus      oleo      246    0.000002        [9.03, 8.98, 8.96]
10   ilheus       pao      246    0.000018      [77.63, 77.0, 78.09]
11   ilheus    tomate      246    0.000160      [43.23, 43.5, 56.13]
12  itabuna    acucar      246    0.000002     [12.11, 12.05, 12.81]
13  itabuna     arroz      246    0.000004     [19.99, 19.92, 19.92]
14  itabuna    banana      246    0.000042     [43.67, 43.91, 43.36]
15  itabuna      cafe      246    0.000003     [16.41, 16.27, 15.55]
16  itabuna     carne      246    0.000052   [202.99, 209.0, 210.84]
17  itabuna   farinha      246    0.000004     [21.75, 21.47, 21.59]
18  itabuna    feijao      246    0.000023     [37.25, 35.95, 35.27]
19  itabuna     leite      246    0.000007     [59.45, 60.46, 60.35]
20  itabuna  manteiga      246    0.000004     [37.37, 36.85, 36.42]
21  itabuna      oleo      246    0.000002         [8.54, 8.83, 8.6]
22  itabuna       pao      246    0.000011     [82.44, 83.21, 83.43]
23  itabuna    tomate      246    0.000141     [51.06, 51.23, 54.39]