In [1]:
import os
import sys
from pathlib import Path
import logging

# Ensure the project root and src/ are on PYTHONPATH.
project_root = Path.cwd().resolve()
if project_root.name == "src":
    project_root = project_root.parent
src_dir = project_root / "src"
for path_entry in (project_root, src_dir):
    if str(path_entry) not in sys.path:
        sys.path.insert(0, str(path_entry))

os.environ["CUDA_VISIBLE_DEVICES"] = "-1"  # Force CPU usage
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"  # Reduce TensorFlow native logs

import pandas as pd
import tensorflow as tf
from utils import train_and_forecast

tf.config.set_visible_devices([], "GPU")  # Disable GPU

# Reduce repeated utility logs during notebook training.
for logger_name in ("utils.data_utils", "src.utils.data_utils"):
    logging.getLogger(logger_name).setLevel(logging.WARNING)

# ============================================================================
# GLOBAL SETTINGS
# ============================================================================

# Available models: 'RNN', 'LSTM', or 'CNN'
MODEL_NAME = "RNN"

# Forecast horizon: 3 or 12 months
FORECAST_HORIZON = 3

# Fixed training parameters
LOOK_BACK = 12
EPOCHS = 150
BATCH_SIZE = 1
SAVE_ONNX = True
SILENCE_TRAINING = True

# Regions and product series
REGIONS = ["ilheus", "itabuna"]
PRODUCTS = [
    "acucar",
    "arroz",
    "banana",
    "cafe",
    "carne",
    "farinha",
    "feijao",
    "leite",
    "manteiga",
    "oleo",
    "pao",
    "tomate",
]

2026-06-05 15:58:23.411100: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

# Previsão preço da cesta básica

## Treinamento de modelos

### Cesta Básica

In [2]:
# Basic basket forecast

print(f"Training basic basket: {MODEL_NAME}, {FORECAST_HORIZON}-month horizon")

basket_summary = []
for region in REGIONS:
    basket_summary.append(
        train_and_forecast(
            region=region,
            series_name="cesta_basica",
            forecast_type="cesta",
            model_name=MODEL_NAME,
            look_back=LOOK_BACK,
            forecast_horizon=FORECAST_HORIZON,
            epochs=EPOCHS,
            batch_size=BATCH_SIZE,
            save_onnx=SAVE_ONNX,
            silence_training=SILENCE_TRAINING,
        )
    )

pd.DataFrame(basket_summary)

Training basic basket: RNN, 3-month horizon

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1780685944.819124  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780685944.819264  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780685944.845437  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780685944.845585  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780685944.872358  427122 mlir_graph_optimization_pass.cc:437] MLIR V1 optimization pass is not enabled
I0000 00:00:1780685986.344249  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780685986.344321  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780685986.368689  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780685986.368748  427122 single_machine.cc:376] Starting new session

    region        series  samples  final_loss                 forecasts
0   ilheus  cesta_basica      243    0.000597   [672.85, 638.7, 630.36]
1  itabuna  cesta_basica      243    0.000400  [666.22, 658.94, 645.08]

### Produtos Individuais

In [3]:
# Product forecasts

total_models = len(REGIONS) * len(PRODUCTS)
print(
    f"Training products: {MODEL_NAME}, {FORECAST_HORIZON}-month horizon "
    f"({total_models} models)"
)

product_summary = []
for region in REGIONS:
    print(f"{region.upper()}: training {len(PRODUCTS)} products...")
    for product in PRODUCTS:
        product_summary.append(
            train_and_forecast(
                region=region,
                series_name=product,
                forecast_type="produtos",
                model_name=MODEL_NAME,
                look_back=LOOK_BACK,
                forecast_horizon=FORECAST_HORIZON,
                epochs=EPOCHS,
                batch_size=BATCH_SIZE,
                save_onnx=SAVE_ONNX,
                silence_training=SILENCE_TRAINING,
                subdir="produtos",
            )
        )
    print(f"{region.upper()}: done")

pd.DataFrame(product_summary)

Training products: RNN, 3-month horizon (24 models)
ILHEUS: training 12 products...

I0000 00:00:1780686027.113025  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686027.113106  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686027.140456  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686027.140518  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686068.217465  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686068.217537  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686068.242424  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686068.242480  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686108.272775  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686108.272901  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686108.297918  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686108.297971  427122 single_machine.cc:376] Starting new session

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x7692a05dd760> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

I0000 00:00:1780686148.483898  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686148.483967  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686148.508462  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686148.508516  427122 single_machine.cc:376] Starting new session

WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x76927c740f40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

I0000 00:00:1780686187.824544  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686187.824612  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686187.849497  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686187.849546  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686227.215911  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686227.215980  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686227.244346  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686227.244405  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686268.868373  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686268.868501  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686268.893981  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686268.894036  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686309.294194  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686309.294318  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686309.320265  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686309.320317  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686349.766765  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686349.766835  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686349.791942  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686349.791998  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686389.969408  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686389.969480  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686389.996259  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686389.996315  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686429.823408  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686429.823496  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686429.850155  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686429.850213  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686471.010249  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686471.010373  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686471.035704  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686471.035759  427122 single_machine.cc:376] Starting new session

ILHEUS: done
ITABUNA: training 12 products...

I0000 00:00:1780686510.523308  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686510.523393  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686510.549780  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686510.549887  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686552.032613  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686552.032690  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686552.058171  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686552.058231  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686592.329097  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686592.329179  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686592.354792  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686592.354851  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686634.363633  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686634.363764  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686634.389426  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686634.389510  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686676.619791  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686676.619916  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686676.650508  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686676.650570  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686716.641084  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686716.641210  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686716.668364  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686716.668414  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686757.966886  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686757.966970  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686757.999908  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686758.000000  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686800.891530  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686800.891599  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686800.915807  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686800.915863  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686841.869562  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686841.869694  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686841.898544  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686841.898670  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686882.964899  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686882.965025  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686882.993684  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686882.993751  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686924.040498  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686924.040648  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686924.067431  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686924.067484  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686962.575912  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686962.575975  427122 single_machine.cc:376] Starting new session
I0000 00:00:1780686962.600808  427122 devices.cc:67] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
I0000 00:00:1780686962.600858  427122 single_machine.cc:376] Starting new session

ITABUNA: done

     region    series  samples  final_loss                 forecasts
0    ilheus    acucar      243    0.000002     [12.52, 12.55, 13.09]
1    ilheus     arroz      243    0.000005     [18.58, 18.36, 18.72]
2    ilheus    banana      243    0.000037      [49.61, 50.0, 50.24]
3    ilheus      cafe      243    0.000003     [18.71, 20.12, 19.19]
4    ilheus     carne      243    0.000126  [215.88, 191.32, 199.27]
5    ilheus   farinha      243    0.000004      [23.8, 23.37, 24.39]
6    ilheus    feijao      243    0.000023     [44.51, 43.76, 41.39]
7    ilheus     leite      243    0.000011     [57.14, 59.04, 58.24]
8    ilheus  manteiga      243    0.000006     [37.48, 36.61, 36.95]
9    ilheus      oleo      243    0.000002        [9.37, 8.84, 8.68]
10   ilheus       pao      243    0.000018     [78.41, 81.02, 78.63]
11   ilheus    tomate      243    0.000155    [102.63, 88.45, 72.72]
12  itabuna    acucar      243    0.000002       [12.53, 12.8, 12.9]
13  itabuna     arroz      243    0.000004     [18.34, 17.19, 17.64]
14  itabuna    banana      243    0.000042     [50.45, 51.17, 49.68]
15  itabuna      cafe      243    0.000003     [16.47, 16.54, 17.78]
16  itabuna     carne      243    0.000052  [204.41, 207.98, 209.29]
17  itabuna   farinha      243    0.000004     [19.44, 19.73, 19.77]
18  itabuna    feijao      243    0.000023     [38.89, 37.82, 36.46]
19  itabuna     leite      243    0.000008     [56.73, 56.16, 59.22]
20  itabuna  manteiga      243    0.000005     [35.85, 35.32, 34.28]
21  itabuna      oleo      243    0.000002        [9.62, 8.94, 9.05]
22  itabuna       pao      243    0.000009     [87.98, 91.42, 92.69]
23  itabuna    tomate      243    0.000138    [104.15, 84.65, 66.85]